version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: fastapi-backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn team5_waterandfish_be.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data: 