[tool.poetry]
name = "team5-waterandfish-be"
version = "0.1.0"
description = ""
authors = ["sweeetpotaooo <sehyun5004@naver.com>"]
readme = "README.md"
packages = [
    { include = "*", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9"
fastapi = ">=0.115.14,<0.116.0"
uvicorn = ">=0.34.3,<0.35.0"
motor = ">=3.3.0,<4.0.0"
pymongo = ">=4.6.0,<5.0.0"
PyJWT = ">=2.8.0,<3.0.0"
httpx = ">=0.24.0,<1.0.0"
python-multipart = ">=0.0.6,<1.0.0"
pydantic-settings = ">=2.0.0,<3.0.0"
bcrypt = "4.0.1"
passlib = {version = "1.7.4", extras = ["bcrypt"]}
sqlalchemy = ">=2.0.0,<3.0.0"
numpy = ">=1.23.0,<2.0.0"
torch = "2.2.2"
sentence-transformers = "<3.0.0"
safetensors = "^0.5.3"

[tool.poetry.group.dev.dependencies]
pymongo = "^4.13.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"