name: Depocaloy to EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd /home/ubuntu/team5-waterandfish-BE
          git pull origin main
          
          # Poetry가 설치되어 있는지 확인
          if ! command -v poetry &> /dev/null; then
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="$HOME/.local/bin:$PATH"
          fi
          
          # Poetry로 의존성 설치 (Linux extras 옵션 제거)
          poetry install --only main
          
          # 서비스 재시작
          sudo systemctl restart waterandfish-backend.service
          sudo systemctl restart waterandfish-websocket-9001.service
          sudo systemctl restart waterandfish-websocket-9002.service
        EOF